/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package santorini_briant_helleux_dufour;

/**
 *
 * @author romdu
 */
public class Santorini_interface_graphique extends javax.swing.JFrame {

    Joueur[] listeJoueurs = new Joueur[2];
    Joueur joueurCourant;
    Plateau plateau = new Plateau();

    /**
     * Creates new form Santorini_interface_graphique
     */
    public Santorini_interface_graphique() {
        initComponents();

        for (int i = 4; i >= 0; i--) {
            for (int j = 0; j < 5; j++) {
                Cellule_graphique cellGraph;
                cellGraph = new Cellule_graphique( plateau[i][j] );
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plateau_jeu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl_joueur1 = new javax.swing.JLabel();
        lbl_joueur2 = new javax.swing.JLabel();
        btn_demarrerpartie = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbl_joueurcourant = new javax.swing.JLabel();
        btn_depl_hd = new javax.swing.JButton();
        btn_depl_haut = new javax.swing.JButton();
        btn_depl_droite = new javax.swing.JButton();
        btn_depl_bd = new javax.swing.JButton();
        btn_depl_bas = new javax.swing.JButton();
        btn_depl_bg = new javax.swing.JButton();
        btn_depl_gauche = new javax.swing.JButton();
        btn_depl_hg = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plateau_jeu.setBackground(new java.awt.Color(0, 204, 204));
        plateau_jeu.setLayout(new java.awt.GridLayout(5, 5));
        getContentPane().add(plateau_jeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 500, 500));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_joueur1.setText("Nom Joueur 1 :");
        jPanel1.add(lbl_joueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 20));

        lbl_joueur2.setText("Nom Joueur 2 :");
        jPanel1.add(lbl_joueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, 20));

        btn_demarrerpartie.setText("jButton1");
        jPanel1.add(btn_demarrerpartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 110, -1));

        jTextField2.setText("jTextField1");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 350, 120));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_joueurcourant.setText("Joueur Courant :");
        jPanel2.add(lbl_joueurcourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, 20));

        btn_depl_hd.setText("jButton1");
        btn_depl_hd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_depl_hdActionPerformed(evt);
            }
        });
        jPanel2.add(btn_depl_hd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 80, 60));

        btn_depl_haut.setText("jButton1");
        jPanel2.add(btn_depl_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 30, 60));

        btn_depl_droite.setText("jButton1");
        jPanel2.add(btn_depl_droite, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 80, 30));

        btn_depl_bd.setText("jButton1");
        jPanel2.add(btn_depl_bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 80, 60));

        btn_depl_bas.setText("jButton1");
        jPanel2.add(btn_depl_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 30, 60));

        btn_depl_bg.setText("jButton1");
        jPanel2.add(btn_depl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 80, 60));

        btn_depl_gauche.setText("jButton1");
        jPanel2.add(btn_depl_gauche, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 80, 30));

        btn_depl_hg.setText("jButton1");
        jPanel2.add(btn_depl_hg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 80, 60));

        jTextField3.setText("jTextField1");
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 110, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 350, 240));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 350, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btn_depl_hdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_depl_hdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_depl_hdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Santorini_interface_graphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Santorini_interface_graphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Santorini_interface_graphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Santorini_interface_graphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Santorini_interface_graphique().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_demarrerpartie;
    private javax.swing.JButton btn_depl_bas;
    private javax.swing.JButton btn_depl_bd;
    private javax.swing.JButton btn_depl_bg;
    private javax.swing.JButton btn_depl_droite;
    private javax.swing.JButton btn_depl_gauche;
    private javax.swing.JButton btn_depl_haut;
    private javax.swing.JButton btn_depl_hd;
    private javax.swing.JButton btn_depl_hg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbl_joueur1;
    private javax.swing.JLabel lbl_joueur2;
    private javax.swing.JLabel lbl_joueurcourant;
    private javax.swing.JPanel plateau_jeu;
    // End of variables declaration//GEN-END:variables
}
